### PR TITLE
Style: center the H2 headings on the homepage

### PR DESCRIPTION
**Pull request by co-bby**
# Description
*centre the H2 headings on the homepage to make the design more consistent and more usable*

# How to Test
*Provide instructions for how to test/run the feature*

# Changes
*changed the code from `float: left to `flexbox`* 

# References
*I live in Ghana. I played Far Cry 5 and decided to search for schools in Montana to apply for grad school in the fall of 2024. I saw  this website during my research and decided to do this little fix*

### CODE REVIEW

**Review by BrendanHar — APPROVED** [review]
👍

**Review by Ethan-Bandy — COMMENTED** [review]
Nice

**Review by Ethan-Bandy — APPROVED** [review]
NIce

**Comment by BrendanHar** [comment]
Old pull request. Closing

**Pull request closed without merging**
